// Directory-wide settings for the shop deployment group. The tests serve it
// over the in-memory transport in internal/memtransport, named "mem".

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: shop/deployment.proto

package shop

import (
	_ "github.com/Paymentbox-com/grpc-service-mesh-go/meshoptions"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_shop_deployment_proto protoreflect.FileDescriptor

const file_shop_deployment_proto_rawDesc = "" +
	"\n" +
	"\x15shop/deployment.proto\x12\x04shop\x1a\x12mesh/options.protoBO\xa2\xb5\x18\x03memZFgithub.com/Paymentbox-com/grpc-service-mesh-go/internal/testproto/shopb\x06proto3"

var file_shop_deployment_proto_goTypes = []any{}
var file_shop_deployment_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shop_deployment_proto_init() }
func file_shop_deployment_proto_init() {
	if File_shop_deployment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shop_deployment_proto_rawDesc), len(file_shop_deployment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shop_deployment_proto_goTypes,
		DependencyIndexes: file_shop_deployment_proto_depIdxs,
	}.Build()
	File_shop_deployment_proto = out.File
	file_shop_deployment_proto_goTypes = nil
	file_shop_deployment_proto_depIdxs = nil
}
