// The reference definitions the tests and docs use. `just proto-test`
// generates internal/testproto from them with grpc-service-mesh-gen.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: shop/order.proto

package shop

import (
	_ "github.com/Paymentbox-com/grpc-service-mesh-go/meshoptions"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Item          *string                `protobuf:"bytes,2,opt,name=item,proto3,oneof" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_shop_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_shop_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_shop_order_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *Order) GetItem() string {
	if x != nil && x.Item != nil {
		return *x.Item
	}
	return ""
}

var File_shop_order_proto protoreflect.FileDescriptor

const file_shop_order_proto_rawDesc = "" +
	"\n" +
	"\x10shop/order.proto\x12\x04shop\x1a\x12mesh/options.proto\x1a\x1bgoogle/protobuf/empty.proto\"E\n" +
	"\x05Order\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x17\n" +
	"\x04item\x18\x02 \x01(\tH\x01R\x04item\x88\x01\x01B\x05\n" +
	"\x03_idB\a\n" +
	"\x05_item2o\n" +
	"\fOrderService\x12!\n" +
	"\x05Place\x12\v.shop.Order\x1a\v.shop.Order\x12<\n" +
	"\x06Placed\x12\v.shop.Order\x1a\x16.google.protobuf.Empty\"\r\x88\xb5\x18\x01\x92\xb5\x18\x05auditBHZFgithub.com/Paymentbox-com/grpc-service-mesh-go/internal/testproto/shopb\x06proto3"

var (
	file_shop_order_proto_rawDescOnce sync.Once
	file_shop_order_proto_rawDescData []byte
)

func file_shop_order_proto_rawDescGZIP() []byte {
	file_shop_order_proto_rawDescOnce.Do(func() {
		file_shop_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shop_order_proto_rawDesc), len(file_shop_order_proto_rawDesc)))
	})
	return file_shop_order_proto_rawDescData
}

var file_shop_order_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_shop_order_proto_goTypes = []any{
	(*Order)(nil),         // 0: shop.Order
	(*emptypb.Empty)(nil), // 1: google.protobuf.Empty
}
var file_shop_order_proto_depIdxs = []int32{
	0, // 0: shop.OrderService.Place:input_type -> shop.Order
	0, // 1: shop.OrderService.Placed:input_type -> shop.Order
	0, // 2: shop.OrderService.Place:output_type -> shop.Order
	1, // 3: shop.OrderService.Placed:output_type -> google.protobuf.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shop_order_proto_init() }
func file_shop_order_proto_init() {
	if File_shop_order_proto != nil {
		return
	}
	file_shop_order_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shop_order_proto_rawDesc), len(file_shop_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shop_order_proto_goTypes,
		DependencyIndexes: file_shop_order_proto_depIdxs,
		MessageInfos:      file_shop_order_proto_msgTypes,
	}.Build()
	File_shop_order_proto = out.File
	file_shop_order_proto_goTypes = nil
	file_shop_order_proto_depIdxs = nil
}
