// Code generated by grpc-service-mesh-gen. DO NOT EDIT.
// source: shop/order.proto

package shop

import (
	"context"
	"github.com/Paymentbox-com/grpc-service-mesh-go/grpcmesh"
	"github.com/Paymentbox-com/service-mesh-go/mesh"
)

// OrderTargets holds one Target per rpc method of OrderService.
var OrderTargets = struct {
	Place  mesh.Target
	Placed mesh.Target
}{
	Place: mesh.Target{
		Segments: []string{"shop", "OrderService", "Place"},
		Kind:     mesh.KindRoute,
		Metadata: map[string]string{
			"transport": "mem",
		},
	},
	Placed: mesh.Target{
		Segments: []string{"shop", "OrderService", "Placed"},
		Kind:     mesh.KindTopic,
		Metadata: map[string]string{
			"transport": "mem",
		},
	},
}

// OrderService is the RPCService for OrderService. A nil field is not
// served.
type OrderService struct {
	Place  func(context.Context, *Order) (*Order, error)
	Placed func(context.Context, *Order) error
}

// Endpoints returns the Endpoints of the ROUTE methods that are set.
func (s OrderService) Endpoints() []mesh.Endpoint {
	var out []mesh.Endpoint
	if s.Place != nil {
		out = append(out, grpcmesh.NewEndpoint(OrderTargets.Place, "", s.Place))
	}
	return out
}

// Subscribers returns the Subscribers of the TOPIC methods that are set.
func (s OrderService) Subscribers() []mesh.Subscriber {
	var out []mesh.Subscriber
	if s.Placed != nil {
		out = append(out, grpcmesh.NewSubscriber(OrderTargets.Placed, "audit", s.Placed))
	}
	return out
}

type orderClient struct{}

// OrderClient calls OrderService through grpcmesh.DefaultTransportRouter.
var OrderClient orderClient

// Place calls the ROUTE method Place.
func (orderClient) Place(ctx context.Context, req *Order, md map[string]string) (*Order, map[string]string, error) {
	return grpcmesh.Call[*Order, *Order](ctx, OrderTargets.Place, req, md)
}

// Placed publishes to the TOPIC method Placed.
func (orderClient) Placed(ctx context.Context, req *Order, md map[string]string) error {
	return grpcmesh.Publish(ctx, OrderTargets.Placed, req, md)
}
