// Custom options defined by the gRPC Service Mesh API.
// Definitions projects import this file unchanged.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: mesh/options.proto

package meshoptions

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Kind says whether a method replies.
type Kind int32

const (
	Kind_ROUTE Kind = 0
	Kind_TOPIC Kind = 1
)

// Enum value maps for Kind.
var (
	Kind_name = map[int32]string{
		0: "ROUTE",
		1: "TOPIC",
	}
	Kind_value = map[string]int32{
		"ROUTE": 0,
		"TOPIC": 1,
	}
)

func (x Kind) Enum() *Kind {
	p := new(Kind)
	*p = x
	return p
}

func (x Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_mesh_options_proto_enumTypes[0].Descriptor()
}

func (Kind) Type() protoreflect.EnumType {
	return &file_mesh_options_proto_enumTypes[0]
}

func (x Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Kind.Descriptor instead.
func (Kind) EnumDescriptor() ([]byte, []int) {
	return file_mesh_options_proto_rawDescGZIP(), []int{0}
}

var file_mesh_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*Kind)(nil),
		Field:         50001,
		Name:          "mesh.kind",
		Tag:           "varint,50001,opt,name=kind,enum=mesh.Kind",
		Filename:      "mesh/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50002,
		Name:          "mesh.consumer_group",
		Tag:           "bytes,50002,opt,name=consumer_group",
		Filename:      "mesh/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50003,
		Name:          "mesh.deployment_group",
		Tag:           "bytes,50003,opt,name=deployment_group",
		Filename:      "mesh/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50004,
		Name:          "mesh.transport",
		Tag:           "bytes,50004,opt,name=transport",
		Filename:      "mesh/options.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// Absent means ROUTE.
	//
	// optional mesh.Kind kind = 50001;
	E_Kind = &file_mesh_options_proto_extTypes[0]
	// Consumer group for the binding generated from this method. Absent means
	// the deployment group.
	//
	// optional string consumer_group = 50002;
	E_ConsumerGroup = &file_mesh_options_proto_extTypes[1]
)

// Extension fields to descriptorpb.FileOptions.
var (
	// Overrides the deployment group name for the file's top-level directory.
	// Absent means the directory name.
	//
	// optional string deployment_group = 50003;
	E_DeploymentGroup = &file_mesh_options_proto_extTypes[2]
	// Names the transport the file's top-level directory is served over.
	// Exactly one file per top-level directory sets it.
	//
	// optional string transport = 50004;
	E_Transport = &file_mesh_options_proto_extTypes[3]
)

var File_mesh_options_proto protoreflect.FileDescriptor

const file_mesh_options_proto_rawDesc = "" +
	"\n" +
	"\x12mesh/options.proto\x12\x04mesh\x1a google/protobuf/descriptor.proto*\x1c\n" +
	"\x04Kind\x12\t\n" +
	"\x05ROUTE\x10\x00\x12\t\n" +
	"\x05TOPIC\x10\x01:@\n" +
	"\x04kind\x12\x1e.google.protobuf.MethodOptions\x18ц\x03 \x01(\x0e2\n" +
	".mesh.KindR\x04kind:G\n" +
	"\x0econsumer_group\x12\x1e.google.protobuf.MethodOptions\x18҆\x03 \x01(\tR\rconsumerGroup:I\n" +
	"\x10deployment_group\x12\x1c.google.protobuf.FileOptions\x18ӆ\x03 \x01(\tR\x0fdeploymentGroup:<\n" +
	"\ttransport\x12\x1c.google.protobuf.FileOptions\x18Ԇ\x03 \x01(\tR\ttransportB<Z:github.com/Paymentbox-com/grpc-service-mesh-go/meshoptionsb\x06proto3"

var (
	file_mesh_options_proto_rawDescOnce sync.Once
	file_mesh_options_proto_rawDescData []byte
)

func file_mesh_options_proto_rawDescGZIP() []byte {
	file_mesh_options_proto_rawDescOnce.Do(func() {
		file_mesh_options_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mesh_options_proto_rawDesc), len(file_mesh_options_proto_rawDesc)))
	})
	return file_mesh_options_proto_rawDescData
}

var file_mesh_options_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mesh_options_proto_goTypes = []any{
	(Kind)(0),                          // 0: mesh.Kind
	(*descriptorpb.MethodOptions)(nil), // 1: google.protobuf.MethodOptions
	(*descriptorpb.FileOptions)(nil),   // 2: google.protobuf.FileOptions
}
var file_mesh_options_proto_depIdxs = []int32{
	1, // 0: mesh.kind:extendee -> google.protobuf.MethodOptions
	1, // 1: mesh.consumer_group:extendee -> google.protobuf.MethodOptions
	2, // 2: mesh.deployment_group:extendee -> google.protobuf.FileOptions
	2, // 3: mesh.transport:extendee -> google.protobuf.FileOptions
	0, // 4: mesh.kind:type_name -> mesh.Kind
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	4, // [4:5] is the sub-list for extension type_name
	0, // [0:4] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mesh_options_proto_init() }
func file_mesh_options_proto_init() {
	if File_mesh_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mesh_options_proto_rawDesc), len(file_mesh_options_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 4,
			NumServices:   0,
		},
		GoTypes:           file_mesh_options_proto_goTypes,
		DependencyIndexes: file_mesh_options_proto_depIdxs,
		EnumInfos:         file_mesh_options_proto_enumTypes,
		ExtensionInfos:    file_mesh_options_proto_extTypes,
	}.Build()
	File_mesh_options_proto = out.File
	file_mesh_options_proto_goTypes = nil
	file_mesh_options_proto_depIdxs = nil
}
