// Code generated by grpc-service-mesh-gen. DO NOT EDIT.
// source: testproto/api_key.proto
//
// This file is hand-written to the shape grpc-service-mesh-gen emits, so the
// grpcmesh tests run without the generator. It is the reference output for
// a directory with transport "mem" and deployment group "testproto".

package testproto

import (
	"context"

	"github.com/Paymentbox-com/grpc-service-mesh-go/grpcmesh"
	"github.com/Paymentbox-com/service-mesh-go/mesh"
)

// ApiKeyTargets holds one Target per rpc method of ApiKeyService.
var ApiKeyTargets = struct {
	Search  mesh.Target
	Created mesh.Target
}{
	Search: mesh.Target{
		Segments: []string{"testproto", "ApiKeyService", "Search"},
		Kind:     mesh.KindRoute,
		Metadata: map[string]string{
			"deployment_group": "testproto",
			"transport":        "mem",
		},
	},
	Created: mesh.Target{
		Segments: []string{"testproto", "ApiKeyService", "Created"},
		Kind:     mesh.KindTopic,
		Metadata: map[string]string{
			"deployment_group": "testproto",
			"transport":        "mem",
			"consumer_group":   "audit",
		},
	},
}

// ApiKeyService is the RPCService for ApiKeyService. A nil field is not
// served.
type ApiKeyService struct {
	Search  func(context.Context, *ApiKey) (*ApiKey, error)
	Created func(context.Context, *ApiKey) error
}

// Endpoints returns the Endpoints of the ROUTE methods that are set.
func (s ApiKeyService) Endpoints() []mesh.Endpoint {
	var out []mesh.Endpoint
	if s.Search != nil {
		out = append(out, grpcmesh.NewEndpoint(ApiKeyTargets.Search, s.Search))
	}
	return out
}

// Subscribers returns the Subscribers of the TOPIC methods that are set.
func (s ApiKeyService) Subscribers() []mesh.Subscriber {
	var out []mesh.Subscriber
	if s.Created != nil {
		out = append(out, grpcmesh.NewSubscriber(ApiKeyTargets.Created, s.Created))
	}
	return out
}

type apiKeyClient struct{}

// ApiKeyClient calls ApiKeyService through grpcmesh.DefaultTransportRouter.
var ApiKeyClient apiKeyClient

// Search calls the ROUTE method Search.
func (apiKeyClient) Search(ctx context.Context, req *ApiKey) (*ApiKey, error) {
	return grpcmesh.Call[*ApiKey, *ApiKey](ctx, ApiKeyTargets.Search, req)
}

// Created publishes to the TOPIC method Created.
func (apiKeyClient) Created(ctx context.Context, req *ApiKey) error {
	return grpcmesh.Publish(ctx, ApiKeyTargets.Created, req)
}
