// Test definitions for the grpcmesh package. Regenerate with `just proto`.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: api_key.proto

package testproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApiKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstName     *string                `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3,oneof" json:"first_name,omitempty"`
	LastName      *string                `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3,oneof" json:"last_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiKey) Reset() {
	*x = ApiKey{}
	mi := &file_api_key_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiKey) ProtoMessage() {}

func (x *ApiKey) ProtoReflect() protoreflect.Message {
	mi := &file_api_key_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiKey.ProtoReflect.Descriptor instead.
func (*ApiKey) Descriptor() ([]byte, []int) {
	return file_api_key_proto_rawDescGZIP(), []int{0}
}

func (x *ApiKey) GetFirstName() string {
	if x != nil && x.FirstName != nil {
		return *x.FirstName
	}
	return ""
}

func (x *ApiKey) GetLastName() string {
	if x != nil && x.LastName != nil {
		return *x.LastName
	}
	return ""
}

var File_api_key_proto protoreflect.FileDescriptor

const file_api_key_proto_rawDesc = "" +
	"\n" +
	"\rapi_key.proto\x12\ttestproto\"k\n" +
	"\x06ApiKey\x12\"\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tH\x00R\tfirstName\x88\x01\x01\x12 \n" +
	"\tlast_name\x18\x02 \x01(\tH\x01R\blastName\x88\x01\x01B\r\n" +
	"\v_first_nameB\f\n" +
	"\n" +
	"_last_nameBCZAgithub.com/Paymentbox-com/grpc-service-mesh-go/internal/testprotob\x06proto3"

var (
	file_api_key_proto_rawDescOnce sync.Once
	file_api_key_proto_rawDescData []byte
)

func file_api_key_proto_rawDescGZIP() []byte {
	file_api_key_proto_rawDescOnce.Do(func() {
		file_api_key_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_key_proto_rawDesc), len(file_api_key_proto_rawDesc)))
	})
	return file_api_key_proto_rawDescData
}

var file_api_key_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_key_proto_goTypes = []any{
	(*ApiKey)(nil), // 0: testproto.ApiKey
}
var file_api_key_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_key_proto_init() }
func file_api_key_proto_init() {
	if File_api_key_proto != nil {
		return
	}
	file_api_key_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_key_proto_rawDesc), len(file_api_key_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_key_proto_goTypes,
		DependencyIndexes: file_api_key_proto_depIdxs,
		MessageInfos:      file_api_key_proto_msgTypes,
	}.Build()
	File_api_key_proto = out.File
	file_api_key_proto_goTypes = nil
	file_api_key_proto_depIdxs = nil
}
