// Code generated by grpc-service-mesh-gen. DO NOT EDIT.

package servicemaps

import (
	"github.com/Paymentbox-com/grpc-service-mesh-go/internal/testproto/shop"
	"github.com/Paymentbox-com/service-mesh-go/mesh"
)

// Mem holds every Target served over transport "mem".
var Mem = mesh.ServiceMap{Targets: []mesh.Target{
	shop.OrderTargets.Place,
	shop.OrderTargets.Placed,
}}
